### ISSUE TITLE
Add button to show all posts again once a filter is selected

### ISSUE THREAD

**Issue by jbrown** [kmicol/productSite#3]
- [x] Add a button that says "All" to the button group in the rename template before the `{{each}}`
- [x] When the `selectedFilter` is `null`, it should have the `btn-primary` class, otherwise it should have the `btn-default` class.
- [x] Clicking the button clears the filter using `{{action (mut selectedFilter) null}}`

**Comment by kmicol** [comment]
It's in the latest build

**Comment by jbrown** [comment]
👍
